### ISSUE TITLE
I18n Translation Issue

### ISSUE THREAD

**Issue by ghost** [excid3/simple_calendar#192]
Rails version 5.1.4

I am having an issue with translations on the calendar, using the default code:

<%= month_calendar do |date| %>
  <%= date %>
<% end %>

Renders the following:

![screen shot 2018-01-20 at 07 27 53](https://user-images.githubusercontent.com/3192599/35181100-973ffdcc-fdb3-11e7-8882-bb0b903039ba.png)

The calendar was working correctly prior to enabling i18n translation in the project, and this is functioning correctly elsewhere. 

I am using the latest version of simple_calendar and have required the css file.

In my language file (en-GB in this example) I have included the following lines:

en-GB:
  activerecord:
    errors:
      messages:
        record_invalid: 'Validation failed: %{errors}'
        restrict_dependent_destroy:
          has_one: "Cannot delete record because a dependent %{record} exists"
          has_many: "Cannot delete record because dependent %{record} exist"
  date:
    abbr_day_names: 
    - Sun
    - Mon
    - Tue
    - Wed
    - Thu
    - Fri
    - Sat

(note there are more lines in the file for other translations)

Any suggestions?

**Comment by donBigote** [comment]
I just added the gem to a rails 5.2 project and I get the same behavior. I changed
`config.i18n.default_locale = :es`
to
`config.i18n.default_locale = :en` 

in application.rb

And the month says April

When I change the default locale to :es, the month says `n`

**Comment by excid3** [comment]
The location where the locales are used is here: https://github.com/excid3/simple_calendar/blob/master/app/views/simple_calendar/_month_calendar.html.erb#L4

If you spot what's wrong, feel free to send me a PR to fix it!

**Comment by dgbtech** [comment]
I fixed this adding the texts to my locale.

es.yml
```
es:
  date:
    month_names: ["", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]
    day_names: ["Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"]
```
