### ISSUE TITLE
i18n with simple calendar

### ISSUE THREAD

**Issue by JanetBanerjee** [excid3/simple_calendar#220]
I want to internationalize the text in simple calendar.  I see the markdown for it is already in the views, I was wondering if there was a locales .yml form included in the gem that I could generate and then translate over.

**Comment by excid3** [comment]
There's only like two custom strings so you can just add them to your normal locales file. Not enough to justify it's own locales file.

```
# config/locales/en.yml 
en:
  simple_calendar:
    previous: "«"
    next: "»"
```
